### ISSUE TITLE
build apk failed

### ISSUE THREAD

**Issue by badboy-tian** [rxlabz/audioplayer#110]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayer'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


The plugin audioplayer could not be built due to the issue above.
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)
```

**Comment by Jackcui68** [comment]
the same issue

**Comment by nikhil08652** [comment]
Same issue

**Comment by mengsiyitiaojie** [comment]
FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/lihong/Documents/fluttersdk/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 122

* What went wrong:
Could not get unknown property 'runtimeConfiguration' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


The plugin audioplayer could not be built due to the issue above.

**Comment by mengsiyitiaojie** [comment]
我也是这个错

**Comment by mengsiyitiaojie** [comment]
求解决

**Comment by rxlabz** [comment]
Sorry for the delay...
the android part of the plugin is now updated ( 0.8.0 : migration to new plugin API & AndroidX ), it should be solved. I close the issue for now, but feel free to open it again if you still have the problem with the last plugin version
